create database if not exists 'book' default character set latin1
collate latin1_swdish_ci;
use book;
CREATE TABLE IF NOT EXISTS `admin` (
  `AId` INT(11) NOT NULL AUTO_INCREMENT,
  `AName` VARCHAR(150) NOT NULL,
  `APass` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`AId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `book` (
  `BId` INT(11) NOT NULL AUTO_INCREMENT,
  `BTitle` VARCHAR(150) NOT NULL,
  `Keywords` VARCHAR(150) NOT NULL,
  `File` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`BId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `comment` (
  `CId` INT(11) NOT NULL AUTO_INCREMENT,
  `BId` INT(11) NOT NULL,
  `SId` INT(11) NOT NULL,
  `Comm` VARCHAR(150) NOT NULL,
  `Logs` date NOT NULL,
   PRIMARY KEY (`CId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `request` ( 
`RId` INT(11) NOT NULL AUTO_INCREMENT, 
`Id` INT(11) NOT NULL, 
`MES` text NOT NULL, 
`Logs` datetime NOT NULL, PRIMARY KEY (`RId`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `Student` ( 
`Id` INT(11) NOT NULL AUTO_INCREMENT, 
`Name` varchar(150) NOT NULL, 
`Pass` varchar(150) NOT NULL, 
`Mail` varchar(150) NOT NULL, 
`Dep` varchar(150) NOT NULL, PRIMARY KEY (`Id`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
